@startuml 

' PATRON SINGLETON

' CLASE PRINCIPAL DEL PATRON.
class Singleton {
    ' Atributos privado que almancena la unica instancia de Singleton.
    - instancia : Singleton
    ' Constructor privado para evitar que se creen instancias desde otra clase.
    - Singleton()
    ' Permite obtener la unica instancia de Singleton.
    + getInstancia() : Singleton
    ' Metodo de ejemplo de la clase.
    + ejecutar() : void
}

' La clase mantiene referencia a su propia instancia para garantizar que existe una unica instancia.
Singleton -> Singleton : mantiene unica instancia 

@enduml 